find untracked files
elisasre/mageutil pull request #61
Opened 2023-12-13 10:20 UTC by jauru

2023-12-14 08:00 UTC, heppu requested changes

2023-12-14 08:00 UTC, heppu commented on git/git.go
> +}
Tälle ois hyvä tehä joku testi ettei tuo `out` sisällä esim yhtä newline merkkiä ja sen takia ole vaikka pidempi ku 0.

2023-12-19 08:06 UTC, heppu requested changes

2023-12-19 08:06 UTC, heppu commented on git/git.go
> +	return nil
Tämä vois olla kokonaisuudessaan näin:
```go
if len(bytes.TrimSpace(out)) > 0 {
	return errors.New("untracked files found")
}
```

2023-12-19 09:10 UTC, heppu approved these changes

2023-12-19 20:31 UTC, zetaab approved these changes

2023-12-19 20:31 UTC, merged